import 'package:get/get_state_manager/src/simple/get_controllers.dart';
import 'package:pueblo_golf_tournament_mobile/dto/request/lookup-division-request-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/request/lookup-leader-board-request-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/request/lookup-payment-channel-accounts-request-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/request/lookup-payment-channels-request-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/request/lookup-player-profile-request-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/request/lookup-player-scores-request-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/request/lookup-player-tee-time-schedule-request-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/request/lookup-scorer-profile-request-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/request/lookup-tee-time-schedule-request-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/request/lookup-tournament-details-request-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/request/lookup-tournament-team-request-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/request/lookup-tournaments-request-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/response/lookup-division-response-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/response/lookup-leader-board-response-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/response/lookup-payment-channel-accounts-response-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/response/lookup-payment-channels-response-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/response/lookup-player-profile-response-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/response/lookup-player-scores-response-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/response/lookup-player-tee-time-schedules-response-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/response/lookup-scorer-profile-response-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/response/lookup-tee-time-schedules-response-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/response/lookup-tournament-details-response-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/response/lookup-tournament-response-dto.dart';
import 'package:pueblo_golf_tournament_mobile/dto/response/lookup-tournament-team-response-dto.dart';

import '../../dto/response/lookup-tournament-holes-response-dto.dart';

abstract class ILookupController extends GetxController {
  Future<LookupTournamentResponseDto> lookupTournaments(
      LookupTournamentsRequestDto payload);
  Future<LookupTournamentDetailsResponseDto> lookupTournamentDetails(
      LookupTournamentDetailsRequestDto payload);
  Future<LookupDivisionResponseDto> lookupDivisions(
      LookupDivisionRequestDto payload);
  Future<LookupTournamentTeamResponseDto> lookupTournamentTeam(
      LookupTournamentTeamRequestDto payload);
  Future<LookupPlayeProfileResponseDto> lookupPlayerProfile(
      LookupPlayeProfileRequestDto payload);
  Future<LookupPlayeProfileResponseDto> lookupPlayerProfileByPersonId(
      LookupPlayeProfileByPersonIdRequestDto payload);
  Future<LookupPaymentChannelsResponseDto> lookupPaymentChannels(
      LookupPaymentChannelsRequestDto payload);
  Future<LookupPaymentChannelAccountsResponseDto> lookupPaymentChannelAccounts(
      LookupPaymentChannelAccountsRequestDto payload);
  Future<LookupTeeTimeScheduleResponse> lookupTeeTimeSchedules(
      LookupTeeTimeScheduleRequest payload);
  Future<LookupPlayerTeeTimeScheduleResponse> lookupPlayerTeeTimeSchedules(
      LookupPlayerTeeTimeScheduleRequest payload);
  Future<LookupTournamentHolesResponseDto> lookupTournamentHoles(
      LookupTournamentDetailsRequestDto payload);
  Future<LookupScorerProfileResponseDto> lookupScorerProfile(
      LookupScorerProfilesRequestDto payload);
  Future<LookupPlayerScoresResponse> lookupPlayerScores(
      LookupPlayerScoresRequest payload);
  Future<LookupLeaderBoardResponseDto> lookupLeaderBoard(
      LookupLeaderBoardRequestDto payload);
}
